#!/bin/sh

# Common
warning_color='\033[0;33m'
no_color='\033[1;33m'

# fzf

## If fzf is not installed, tell the user it is a good idea to install fzf
if ! command -v fzf &> /dev/null
then
    echo -e "${warning_color}fzf is not installed, it is a good idea to install it for better experience${no_color}"
fi

# eza

## If eza is installed, replace ls with eza, else tell the user is is a good idea to install eza
if command -v eza &> /dev/null
then
    alias ls='eza'
else
    echo -e "${warning_color}eza is not installed, it is a good idea to install it for better ls experience${no_color}"
fi

# ls

alias l='ls -la'

# podman

## If we do not find docker, we create an alias for podman
if ! command -v docker &> /dev/null
then
    alias docker='podman'
fi

# docker

## docker Logs
alias dl='docker ps --format "{{.Names}}" | fzf | xargs docker logs -f --tail 100'

## docker Restart
alias dr='docker ps --format "{{.Names}}" | fzf | xargs docker restart'

## docker Stop
alias ds='docker ps --format "{{.Names}}" | fzf | xargs docker stop'

# docker compose
alias dc='docker compose'

## docker compose Logs
alias dcl='docker compose ls | tail -n +2 | fzf | rev | cut -d" " -f1 | rev | sed "s#docker-compose.yml##" | xargs -I {} sh -c "cd {} && docker compose logs -f --tail 100"'

## docker compose Ps
alias dcp='docker compose ls | tail -n +2 | fzf | rev | cut -d" " -f1 | rev | sed "s#docker-compose.yml##" | xargs -I {} sh -c "cd {} && docker compose ps"'

## docker compose Restart
alias dcr='docker compose ls | tail -n +2 | fzf | rev | cut -d" " -f1 | rev | sed "s#docker-compose.yml##" | xargs -I {} sh -c "cd {} && docker compose restart"'

## docker compose Down
alias dcd='docker compose ls | tail -n +2 | fzf | rev | cut -d" " -f1 | rev | sed "s#docker-compose.yml##" | xargs -I {} sh -c "cd {} && docker compose down"'

# thefuck

## If thefuck is installed, install command, else tell the user is is a good idea to install thefuck

if command -v thefuck &> /dev/null
then
    eval $(thefuck --alias)
else
    echo -e "${warning_color}thefuck is not installed, it is a good idea to install it.${no_color}"
fi
